name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] #, macos-10.15, windows-2019]
        node: [18]
    name: ${{ matrix.os }} and node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Download testing data
        shell: bash
        run: |
          curl -OL https://github.com/Kitware/itk-vtk-viewer/releases/download/v14.5.0/itk-vtk-viewer-testing-data.tar.gz
          tar xvzf ./itk-vtk-viewer-testing-data.tar.gz -C test/

      - name: Build
        run: npm run build

      - name: Test
        if: ${{ runner.os == 'Linux' }}
        run: |
          npm run test:downloadData
          # Allow writing test/output.html
          sudo chmod -R 777 test
          # To debug, run `./test/run.sh -d`
          npm run test:headless

      - uses: ashley-taylor/junit-report-annotations-action@v1.0
        if: ${{ always() && runner.os == 'ubuntu-18.04' }}
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: 'test/TESTS-*.xml'

      - uses: actions/upload-artifact@v1
        if: ${{ always() && runner.os == 'ubuntu-18.04' }}
        with:
          name: 'Node${{ matrix.node}}TestOutput'
          path: test/output.html
